[project]
name = "opener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=4.0.10",
    "groq>=1.7.0",
    "pyaudio>=0.2.14",
    "pyautogui>=0.9.54",
    "pygetwindow>=0.0.9",
    "python-dotenv>=1.0.0",
    "requests>=2.34.2",
    "websocket-client>=1.9.2",
    "websockets>=15.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.3",
]
